name: Generate PDF files
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          for d in posts/*/; do
            mkdir -p pdfs/$d
          done
      - name: convert md to pdf
        run: |
          find ./posts/ -iname '*.md' -type f -exec sh -c 'pandoc ${0} -o pdfs/${0%.md}.pdf --metadata-file=pdf-styles/meta_aao-latex.yaml  --template=pdf-styles/argonl_latex.template --pdf-engine=xelatex --lua-filter=pdf-styles/inferenceline.lua' {} \;
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: pdfs
